	#.
	#Stress values
	[stressValues.v1]

		#.
		#.
		#[in Stress Units]
		#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
		[stressValues.v1.impact]
			resistor = 16.0
